### ISSUE TITLE
XSS Injection into Markdown

### ISSUE THREAD

**Issue by a8q** [cespare/pastedown#20]
You can inject XSS into markdown by doing:
`[totallyharmlesslink](javascript:window.onerror=alert;throw%201)`

An example is at:
http://pastedown.ctrl-c.us/#HpczYb1hWr1uCovQOSvKXJDKAp4.markdown

**Comment by cespare** [comment]
Thanks. Looks like I should pass blackfriday output through [bluemonday](https://github.com/microcosm-cc/bluemonday).

**Comment by a8q** [comment]
That would seem to be a good solution!

**Comment by cespare** [comment]
Fixed; the HTML is sanitized now.

Example: https://pastedown.ctrl-c.us/#aO5AFminabsB83RlKT5bhA5pofg.markdown (will expire in a week)
